# Generated by Django 5.0.7 on 2024-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('d_day', models.DateField()),
                ('party_room_address', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
