# Generated by Django 5.0.7 on 2024-09-16 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cake_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(default=0)),
                ('light', models.IntegerField(default=0)),
                ('deco1', models.IntegerField(default=0)),
                ('deco2', models.IntegerField(default=0)),
                ('deco3', models.IntegerField(default=0)),
                ('deco4', models.IntegerField(default=0)),
                ('deco5', models.IntegerField(default=0)),
                ('deco6', models.IntegerField(default=0)),
                ('deco7', models.IntegerField(default=0)),
                ('deco8', models.IntegerField(default=0)),
                ('deco9', models.IntegerField(default=0)),
                ('deco10', models.IntegerField(default=0)),
                ('deco11', models.IntegerField(default=0)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('background', models.IntegerField(default=0)),
                ('sent_by', models.CharField(max_length=225)),
                ('font', models.IntegerField(default=0)),
                ('matrix', models.IntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
