# Generated by Django 5.0.7 on 2024-08-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.CharField(max_length=225),
        ),
    ]
