# Generated by Django 5.0.7 on 2024-08-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_message_sent_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake_custom',
            old_name='syrup',
            new_name='props',
        ),
    ]
